### ISSUE TITLE
The use of WGET

### ISSUE THREAD

**Issue by madslundgaard** [chrisspen/django-sec#11]
Is the use of WGET nessesary (maybe for the parallel processing)? I have rewritten to use 'requests' module instead. I am on windows and don´t want to install WGET.

**Comment by chrisspen** [comment]
I've switched the download to a pure-Python wget.

**Comment by madslundgaard** [comment]
Nice! 👍 Didn't even know that the Python version existed. (Bit if a Python n00b I am) I guess that it in some way is better than the requests.download in the current case, yes?
