### ISSUE TITLE
SEC has closed the FTP site, migrate to HTTP

### ISSUE THREAD

**Issue by madslundgaard** [chrisspen/django-sec#13]
SEC has closed the FTP download option with end of 2016. The index download uses this option. This means that 'sec_import_index.py' line 129 should be:
```python
url = 'https://www.sec.gov/Archives/edgar/full-index/%d/QTR%d/company.zip' % (year, quarter)
```

**Comment by chrisspen** [comment]
Good to know. Thanks.

**Comment by robomotic** [comment]
For reference this is the official fee ddescription:
https://www.sec.gov/edgar/searchedgar/accessing-edgar-data.htm
