### ISSUE TITLE
invalid syntax when installing new version

### ISSUE THREAD

**Issue by robomotic** [chrisspen/django-sec#2]
Hello Chriss,
I am getting an invalid syntax now when I install from pip, it seems to be just some extra tabs, it doesn't affect the build but best to remove them .

>   Found existing installation: django-sec 0.3.3
>     Uninstalling django-sec:
>       Successfully uninstalled django-sec
>   Running setup.py install for django-sec
>       File "/usr/local/lib/python2.7/dist-packages/django_sec/management/commands/sec_mark_units.py", line 75
>     
>         ^
>     SyntaxError: invalid syntax
>     
>     
>     warning: no files found matching '*' under directory 'chroniker/tests/fixtures'
> Successfully installed django-sec
> Cleaning up...

**Comment by chrisspen** [comment]
This has been fixed in master.
