### ISSUE TITLE
sec_import_attrs parsing all CIKS instead of the selected ones

### ISSUE THREAD

**Issue by robomotic** [chrisspen/django-sec#3]
Hello there,
I think there is another bug potentially, I only have marked one company for download but when I run:

> python manage.py sec_import_attrs --start-year=2016 --end-year=2017  --form=10-Q,10-K
> 
> Running process: {'start_year': '2016', 'show_pending': False, 'force': False, 'verbose': False, 'settings': None, 'cik': None, 'pythonpath': None, 'verbosity': 1, 'traceback': None, 'multi': 0, 'forms': '10-Q,10-K', 'no_color': False, 'end_year': '2017', 'quarter': None}
> total_count: 7114
> None [          ] 0 of ? ?% eta=?: 7114 total rows.
> None [          ] 1 of 7114 0% eta=2016-05-05 05:14:06.056550+00:00: Processing index edgar/data/1006045/0001564590-16-015763.txt.

It's parsing every company in the database.

**Comment by chrisspen** [comment]
You're correct. I've fixed this and updated the unittest to confirm function of the company load flag.
