### ISSUE TITLE
cannot resolve ticker in search admin view

### ISSUE THREAD

**Issue by robomotic** [chrisspen/django-sec#4]
Hello,
I think this is another foreign key issue introduced in Django 1.9.
If you go on : /admin/django_sec/company/
Put a company name say Verdier I get:

> FieldError at /admin/django_sec/company/
> Cannot resolve keyword '_ticker' into field. Choices are: attributes, cik, filings, load, max_date, min_date, name
> Request Method:   GET
> Request URL:  http://localhost:8000/admin/django_sec/company/?q=Verdier
> Django Version:   1.9
> Exception Type:   FieldError
> Exception Value:  
> Cannot resolve keyword '_ticker' into field. Choices are: attributes, cik, filings, load, max_date, min_date, name
> Exception Location:   /usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py in names_to_path, line 1330
> Python Executable:    /usr/bin/python
> Python Version:   2.7.9
> Python Path:  
> ['/home/pi/Documents/DjangoSec',
>  '/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-arm-linux-gnueabihf',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages/gtk-2.0',
>  '/usr/lib/pymodules/python2.7']
> Server time:  Mon, 2 May 2016 22:05:30 +0000

**Comment by mathieu660** [comment]
Also the ticker row is empty in the database...

**Comment by chrisspen** [comment]
This has been fixed.
