### ISSUE TITLE
Migrations not functional on Django 1.10.4 and Python 3.5.2

### ISSUE THREAD

**Issue by lilott8** [chrisspen/django-sec#6]
I had to alter: https://github.com/chrisspen/django-sec/blob/master/django_sec/migrations/0001_initial.py#L63

By removing the seemingly erroneous 'b' preceding the 'ticker' string.

**Comment by mathieu660** [comment]
Thanks. Fixed some stuff on my Python 3.5. Are you able to do a sec_import_index ? I receive errors...

**Comment by chrisspen** [comment]
I've confirmed this, and modified by unittests to catch this in the future. The sec_import_index error should now be fixed as well.
